Integrate sentry
IFRCGo/go-risk-module-api pull request #3
Opened 2023-02-09 12:28 UTC by Rup-Narayan-Rajbanshi

## Changes
- Integrate sentry

2023-02-10 04:05 UTC, thenav56 requested changes
Let's update docker-compose as well. For user-defined variables like DJANGO_SECRET_KEY let's not forget to use ?err

2023-02-10 04:05 UTC, thenav56 commented on risk_module/settings.py
> +    CELERY_REDIS_URL=(str, 'redis://redis:6379/0'),
Let's define this in docker-compose.yml instead
```suggestion
    CELERY_REDIS_URL=str,
```

2023-02-10 04:05 UTC, thenav56 commented on risk_module/settings.py
> +    SENTRY_DSN=str,
```suggestion
    SENTRY_DSN=(str, None),
```

2023-02-10 04:05 UTC, thenav56 commented on risk_module/settings.py
> +    SENTRY_DSN=str,
This is a optional value
```suggestion
    SENTRY_DSN=(str, None),
```

2023-02-10 04:05 UTC, thenav56 commented on risk_module/settings.py
> +    DATABASE_PORT=str,
```suggestion
    DATABASE_PORT=(int, 5432),
```

2023-02-10 04:05 UTC, thenav56 commented on risk_module/settings.py
> +    DJANGO_ALLOWED_HOST=(str, '*'),
```suggestion
    DJANGO_ALLOWED_HOSTS=(list, ['*']),
```

2023-02-10 04:05 UTC, thenav56 commented on risk_module/settings.py
> +ALLOWED_HOSTS = ['server', env('DJANGO_ALLOWED_HOST')]
```suggestion
ALLOWED_HOSTS = ['server', *env('DJANGO_ALLOWED_HOSTS')]
```

2023-02-13 05:43 UTC, thenav56 approved these changes

2023-02-13 05:43 UTC, thenav56 commented
@k9845 Please review and merge this.

2023-02-13 07:13 UTC, k9845 approved these changes

2023-02-13 07:14 UTC, merged